# Generated by Django 5.2.3 on 2025-06-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aacup',
            fields=[
                ('aacup_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.BooleanField()),
                ('peso', models.BooleanField()),
                ('user', models.BooleanField()),
                ('coordinator', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ched',
            fields=[
                ('ched_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompTechJob',
            fields=[
                ('comp_tech_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('import_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_year', models.IntegerField()),
                ('import_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qpro',
            fields=[
                ('qpro_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InfoSystemJob',
            fields=[
                ('info_system_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_comptechjobs', to='shared.comptechjob')),
            ],
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='info_system_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infosystemjobs', to='shared.infosystemjob'),
        ),
        migrations.CreateModel(
            name='InfoTechJob',
            fields=[
                ('info_tech_jobs_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_comptechjobs', to='shared.comptechjob')),
                ('info_systems_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_infosystemjobs', to='shared.infosystemjob')),
            ],
        ),
        migrations.AddField(
            model_name='infosystemjob',
            name='info_tech_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='info_tech_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_infotechjobs', to='shared.infotechjob'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('standard_id', models.AutoField(primary_key=True, serialize=False)),
                ('aacup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.aacup')),
                ('ched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.ched')),
                ('qpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.qpro')),
            ],
        ),
        migrations.AddField(
            model_name='qpro',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qpros', to='shared.standard'),
        ),
        migrations.CreateModel(
            name='ExportedFile',
            fields=[
                ('exported_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('exported_date', models.DateTimeField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_files', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='ched',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheds', to='shared.standard'),
        ),
        migrations.AddField(
            model_name='aacup',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aacups', to='shared.standard'),
        ),
        migrations.CreateModel(
            name='Suc',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_comptechjobs', to='shared.comptechjob')),
                ('info_system_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_infosystemjobs', to='shared.infosystemjob')),
                ('info_tech_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_infotechjobs', to='shared.infotechjob')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suc_sucs', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='infotechjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infotechjob_sucs', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='infosystemjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosystemjob_sucs', to='shared.suc'),
        ),
        migrations.AddField(
            model_name='comptechjob',
            name='suc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptechjob_sucs', to='shared.suc'),
        ),
        migrations.CreateModel(
            name='TrackerForm',
            fields=[
                ('tracker_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.standard')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='tracker_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='shared.trackerform'),
        ),
        migrations.CreateModel(
            name='HighPosition',
            fields=[
                ('high_position_id', models.AutoField(primary_key=True, serialize=False)),
                ('aacup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_positions', to='shared.aacup')),
                ('tracker_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_positions', to='shared.trackerform')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_username', models.CharField(max_length=100)),
                ('acc_password', models.DateField()),
                ('user_status', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_resume', models.CharField(blank=True, max_length=255, null=True)),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.accounttype')),
                ('import_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shared.import')),
            ],
        ),
        migrations.AddField(
            model_name='trackerform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_forms', to='shared.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(max_length=100)),
                ('notifi_content', models.TextField()),
                ('notif_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shared.user')),
            ],
        ),
        migrations.AddField(
            model_name='import',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='shared.user'),
        ),
    ]
