# Generated by Django 5.2.3 on 2025-06-29 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.BooleanField(default=False)),
                ('peso', models.BooleanField(default=False)),
                ('user', models.BooleanField(default=False)),
                ('coordinator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackerForm',
            fields=[
                ('tracker_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user_mobile.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user_mobile.trackercategory'),
        ),
        migrations.AddField(
            model_name='trackercategory',
            name='tracker_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user_mobile.trackerform'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctu_id', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='CTU ID must be exactly 7 digits.', regex='^\\d{7}$')])),
                ('acc_username', models.CharField(max_length=100)),
                ('acc_password', models.CharField(max_length=255)),
                ('user_status', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(blank=True, max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_bio', models.TextField(blank=True, null=True)),
                ('profile_resume', models.CharField(blank=True, max_length=255, null=True)),
                ('year_graduated', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_mobile.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(max_length=100)),
                ('notif_content', models.TextField()),
                ('notif_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_mobile.user')),
            ],
        ),
    ]
